#mRankup Configuração
database:
    type: sqlite # ou "sqlite"
    mysql:
        host: localhost
        port: 3306
        database: plugin_db
        username: root
        password: password
    sqlite:
        path: plugins/mRankup/database.db

rank-config:
    auto-rank: false #Apos ativar a meta de rank o jogador upa automaticamente sem precisar digitar /rankup
    delay-auto-rank: 5 #Verificação de 5s


topRank-Chat:
    enable: true

topRanks-Holograma: #Depende do plugin Holography(1.7.10 até 1.19) ou DecentHolograma(Versão mais recente)
    enable: true #Ativar?
    min-top: 1 #Irá começar do top 1
    max-top: 10 #Até o top 10
    top-empty: '§8* §8Ninguem'
    update: 25 #minutos, atualiza a cada 25 minutos
    holograma-lines:
        - ''
#mrankup setRankMinion <numero do top> #Não funciona nas versões abaixo de 1.8
topRank-Minions:
    enable: true
    lore:
        - ''
        - ''

